apiVersion: rbac.authorization.k8s.io/v1
kind: User
metadata:
  name: ivanov_ii@test.com
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: User
metadata:
  name: petrov_pp@test.com
  apiGroup: rbac.authorization.k8s.io